stages:
  training:
    cmd: python src/DimondPricePrediction/pipelines/training_pipeline.py
    deps:
      - src/DimondPricePrediction/pipelines/training_pipeline.py
      - src/DimondPricePrediction/components/data_ingestion.py
      - src/DimondPricePrediction/components/data_transformation.py
      - src/DimondPricePrediction/components/model_trainer.py
      - src/DimondPricePrediction/components/model_evaluation.py

    outs:
      - artifacts/raw.csv
      - artifacts/test_data.csv
      - artifacts/train_data.csv
      - artifacts/preprocessor.pkl
      - artifacts/model.pkl